### ISSUE TITLE
不支持表格

### ISSUE THREAD

**Issue by pkptzx** [jijinggang/MarkdownEditor#10]
现在主流的都支持表格了...
赶紧支持啊....要不然真没法用了...

不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格不支持表格

**Comment by jijinggang** [comment]
其实是支持的，你试试这个
Id  | Name
--- | ---
1  | John
2  | Mary
