### ISSUE TITLE
点击超链接的错误

### ISSUE THREAD

**Issue by zhy755788055** [jijinggang/MarkdownEditor#13]
1、点击本文档内的超链接后预览界面显示为空，并且如果不修改md文件，无法查看预览。
2、查看\编辑按钮不能在关闭后保存状态

**Comment by jijinggang** [comment]
我更新了1.1版本,解决了上面的问题,点击超链接后,会用外部工具打开超链接对应的文件或网站
参见https://github.com/jijinggang/MarkdownEditor/releases/tag/1.1
