### ISSUE TITLE
文件修改标志

### ISSUE THREAD

**Issue by zhy755788055** [jijinggang/MarkdownEditor#14]
文件是否修改无法在界面上看出来，建议加个*号表示已经修改，ctrl+z的撤销也有问题

**Comment by jijinggang** [comment]
我更新了1.1版本,修改时在标题栏加上了*号; ctrl+z的撤销目前与windows记事本的处理方式一样,只有一次撤销,如果要做到Word中类似的Undo/Redo,会有较大的资源开销,目前感觉作用不大,先不考虑加入.

参见https://github.com/jijinggang/MarkdownEditor/releases/tag/1.1)
