### ISSUE TITLE
上次邮箱中,提到的软件过份简单的,问题,快半年了还没改进

### ISSUE THREAD

**Issue by ugksoft** [jijinggang/MarkdownEditor#15]
1.默认阅读状态,大部分人只是做为阅读器的,并不去改东西的
2.转到外部域名时,跳转到多页标页,或是外部浏览器上
3.前进后退功能,有些可以按alt+<>来完成,但是有些地方,没办法跳转
4.文件的关联的图标太难看,建议换成exe显示的图标,或其它淡雅,素朴的,
5.好像还有,忘了,具体你翻下邮件吧

**Comment by jijinggang** [comment]
更新到了1.1版本, 解决了大部分问题
参见https://github.com/jijinggang/MarkdownEditor/releases/tag/1.1

**Comment by vaclavmuller** [comment]
Thank you. ♥

**Comment by ugksoft** [comment]
OK,你可以收贴了
