### ISSUE TITLE
导出PDF

### ISSUE THREAD

**Issue by ixjhuang** [jijinggang/MarkdownEditor#20]
首先非常感谢作者，谢谢你做了个这么简洁好用的软件，而且还开源了，特别棒。
然后我想请问一下可以添加导出PDF的功能吗？
感觉导出PDF功能挺重要的呢。

如果有时间的话可以考虑一下噢，然后想再次表达一下对你的感谢。

**Comment by jijinggang** [comment]
在右侧查看窗口可以另存为单独的html文件供其他人查看,不知道这个能否满足你的需要; html转pdf的在线工具有很多,当然稍微要麻烦一些。
如果我找到轻量的库，可以尝试加进去
