### ISSUE TITLE
写注册表和连接网络

### ISSUE THREAD

**Issue by keman1984** [jijinggang/MarkdownEditor#21]
首先非常感谢作者，谢谢你做了个这么简洁好用的软件，而且还开源了，特别棒。
但是，我用这着OMODO，所以
每次启动都写注册表和连接网络是。。。必须的吗？

**Comment by jijinggang** [comment]
删除了所有跟注册表有关的操作, 如果想把MarkdownEditor设置为.md文件的默认编辑器, 直接用windows资源管理器中的"打开方式->选择其他程序->选择MarkdownEditor.exe"即可; MarkdownEditor并不需要连接网络
