### ISSUE TITLE
能否在左边增加一个目录树或者工程管理

### ISSUE THREAD

**Issue by bitbegin** [jijinggang/MarkdownEditor#9]
这个工具好像记事本，好小巧！

我想问一下，能否在左边增加一个目录树或者工程管理（类似sublime那样的也行），这样我可以把它当笔记本来用了。

**Comment by jijinggang** [comment]
这个功能目前不太想加，主要原因是类似的超强功能编辑器已经很多，也不大可能做出更好用的。MarkdownEditor不是他们的替代品，只想做这个最简单的事情，不然估计你也不想用了。

**Comment by tinygg** [comment]
用这个编辑器就是因为它够简洁.

**Comment by kehehee1** [comment]
非常不错的小工具，不过Ctrl+A没法用，只能鼠标右键全选很别扭啊
